apiVersion: v1
kind: Pod
metadata:
  name: nginx-{{.Namespace}}
  namespace: {{.Namespace}}
spec:
  containers:
  - name: hello
    image: busybox:1.28
    command: ['sh', '-c', 'echo "{{.Message}}" && sleep 3600']
  restartPolicy: OnFailure
